application: forecastaer
version: 1
runtime: python27
api_version: 1
threadsafe: true

# URLS and apps
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /images
  static_dir: templates/images

- url: /data
  static_dir: data
  application_readable: true

- url: .*
  script: handlers.app


#Libraries
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


#Skip these files
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(old_files/.*)
- ^(logs/.*)


#FOR USE IN DEV

#dev_appserver.py ./

#FOR USE IN PRODUCTION

#appcfg.py update ./

